# Generated by Django 3.2.20 on 2023-07-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../user-rectangle-duotone_ssdjcr', upload_to='images/'),
        ),
    ]
